### PR TITLE
Pzc form research

### PR DESCRIPTION
**Pull request by paulzimmclay**
## Link to Ticket

#2 

This PR is the register account form, including:

- Form
- Rejection of existing account
- Creation of new account

## Steps to Test

Steps to test

```
git fetch --all
git checkout pzc-form-research
```
On load, register new account page will load
Fill in fields and submit. 
IF email address is not already in DB, user will be added
IF email address is already in DB, user will not be added, and warning div will display

## Impacted Areas in Application

Login page, Database

## Mentions @username

@jeremiah3643

### CODE REVIEW

**Comment by MrErin** [comment]
A few issues:
1.) Need to add a password field so user can set own password
2.) Need to add a text input for a URL to a user's image (no need for a file upload)
3.) The form needs to post to a field in the database called "first" instead of "firstname"
4.) The form needs to post to a field in the database called "last" instead of "lastname"

**Comment by paulzimmclay** [comment]
@MrErin ok, made those changes.

**Comment by MrErin** [comment]
@paulzimmclay 
When I create a new user, whatever option selected in the location dropdown is the value saved to the database for the password and image fields as well.

**Comment by paulzimmclay** [comment]
@MrErin fixed!

**Comment by MrErin** [comment]
🚢

**Pull request merged**
